name: Create Issue
on:
  workflow_dispatch:
  push: # Trigger on push events
    branches:
      - master
jobs:
  rotate-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@v4
        with:
          repository: vboctor/action-rotate-version
      - name: Run Rotate Version Action
        id: rotate-version
        uses: vboctor/action-rotate-version@master
        with:
          url: 'https://salmanshafiq.mantishub.io'
          api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
          project: 'MyProject'
          placeholder-name: 'vNext'
          release-name: "1.20.0"
          next-release-in-days: 7
      - name: get output
        run: echo  ${{ steps.rotate-version.outputs.version-id }}
          
      # - name: create version
      #   uses: salman-shafique/mh-actions/create-mantishub-version@main
      #   with:
      #     url: 'https://salmanshafiq.mantishub.io'
      #     api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
      #     project-id: '1'
      #     name: 'V1.2.0'
      #     description: 'relese version 1.2'
      #     released: false
      #     obsolete: false
      #     timestamp: '2024-09-20'


          
