name: Create Issue
on:
  workflow_dispatch:
  push: # Trigger on push events
    branches:
      - master
jobs:
  create-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@v4
        with:
          repository: vboctor/action-create-version
      - name: Run create Version Action
        id: create-version
        uses: vboctor/action-create-version@master
        with:
          url: 'https://salmanshafiq.mantishub.io'
          api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
          project: 'MyProject'
          name: 'v1.3.13'
          description: |
            Release Version 1.1.13
            For bugs fixes
          released: false
          obsolete: true
          timestamp: '2025-09-20'
      - name: get output
        run: echo  ${{ steps.create-version.outputs.version-id }}
          
      # - name: create version
      #   uses: salman-shafique/mh-actions/create-mantishub-version@main
      #   with:
      #     url: 'https://salmanshafiq.mantishub.io'
      #     api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
      #     project-id: '1'
      #     name: 'V1.2.0'
      #     description: 'relese version 1.2'
      #     released: false
      #     obsolete: false
      #     timestamp: '2024-09-20'


          
