name: Create Issue
on:
  workflow_dispatch:
  push: # Trigger on push events
    branches:
      - master
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@v4
        with:
          repository: vboctor/action-create-issue
      - name: Run create issue Action
        id: create-issue
        uses: vboctor/action-create-issue@master
        with:
          url: 'https://salmanshafiq.mantishub.io'
          api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
          project: 'MyProject'
          summary: "Build is broken"
          description: |
            Unable to submit form.
            Page loading error
          category: 'General'
      - name: get output
        run: echo  ${{ steps.create-issue.outputs.issue-id }}
          
      # - name: create version
      #   uses: salman-shafique/mh-actions/create-mantishub-version@main
      #   with:
      #     url: 'https://salmanshafiq.mantishub.io'
      #     api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
      #     project-id: '1'
      #     name: 'V1.2.0'
      #     description: 'relese version 1.2'
      #     released: false
      #     obsolete: false
      #     timestamp: '2024-09-20'


          
