name: Create Issue
on:
  workflow_dispatch:
  push: # Trigger on push events
    branches:
      - master
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private action repository
        uses: actions/checkout@v2
        with:
          repository: salman-shafique/mh-actions
          token: ${{ secrets.ACTIONS_PAT }}

      - name: create issue
        uses: salman-shafique/mh-actions@main
        with:
          url: 'https://salmanshafiq.mantishub.io/api/rest/issues'
          api-key: 'NdemqEpCFK3d5tX_b7bN_0nVR1uySVg1'
          project-id: '1'
          summary: 'New issue created via GitHub Actions'
          description: 'Details of the issue...'
